spring:
  application:
    name: scores-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/covid_lore?useSSL=false&serverTimezone=UTC
    username: springstudent
    password: springstudent
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/MyRealm
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 0