spring:
  application:
    name: resource-example
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/MyRealm
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 0
