spring:
  application:
    name: post-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/covid_lore?useSSL=false&serverTimezone=UTC
    username: springstudent
    password: springstudent
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/