server:
  port: 8090
spring:
  application:
    name: cloud-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: postModule
#          uri: lb://post-client
#          predicates:
#            - Path=/forum/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

secret: mysecret