server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      globalcors:
          cors-configurations:
            '[/**]':
              allowed-origins: "http://localhost:1234"
              allowed-methods: "*"
              allowed-headers: "*"
              allow-credentials: true
      routes:
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/posts/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/comment/**
        - id: scores-service
          uri: lb://scores-service
          predicates:
              - Path=/score/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE