spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://192.168.0.103:8080/realms/MyRealm/protocol/openid-connect/token
            authorization-uri: http://192.168.0.103:8080/realms/MyRealm/protocol/openid-connect/auth
            user-info-uri: http://192.168.0.103:8080/realms/MyRealm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          keycloak-login-client:
            provider: keycloak
            client-id: spring-login-client
            client-secret: 9FUSyoA8H9EZZPlOygqcjTe5AxHyEZ1E
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.103:8080/realms/MyRealm
          jwk-set-uri: http://192.168.0.103:8080/realms/MyRealm/protocol/openid-connect/certs